apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: elasticsearch
spec:
  providerConfigRef:
    name: helm-provider
  forProvider:
    chart:
      name: elasticsearch
      repository: https://charts.bitnami.com/bitnami
      version: 17.1.1
    namespace: logging
    wait: true
    values:
      master:
        replicas: 1

