apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: fluent-bit
spec:
  providerConfigRef:
    name: helm-provider
  forProvider:
    chart:
      name: fluent-bit
      repository: https://fluent.github.io/helm-charts
      version: 0.19.2
    namespace: logging
    wait: true
    values:
      config:
        outputs: |
          [OUTPUT]
              Name es
              Match kube.*
              Host elasticsearch-master
              Logstash_Format On
              Retry_Limit False
          [OUTPUT]
              Name es
              Match host.*
              Host elasticsearch-master
              Logstash_Format On
              Logstash_Prefix node
              Retry_Limit False
      daemonSetVolumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      daemonSetVolumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true


