apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sa-creator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "watch", "list", "create", "delete", "edit", "patch" ]
