apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-helm-namespace-creator
subjects:
- kind: ServiceAccount
  name: crossplane-provider-helm-17449053f350
  namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io
