apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knative-eventing-admin
rules:
- apiGroups: ["messaging.knative.dev"]
  resources: ["inmemorychannels"]
  verbs: ["get", "list", "watch", "update", "delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-admin
subjects:
- kind: ServiceAccount
  name: eventing-controller
  namespace: knative-eventing
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: knative-eventing-admin
  apiGroup: rbac.authorization.k8s.io
