apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xjstacks.devops.kearos.net
spec:
  group: devops.kearos.net
  names:
    kind: XJStack
    plural: xjstacks
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                storageSize:
                  type: string
                required:
                - storageSize
            required:
            - parameters
