apiVersion: devops.kearos.net/v1alpha1
kind: XJStack
metadata:
  namespace: jenkins
  name: my-jstack-prod
  annotations:
    # The external name annotation has special meaning in Crossplane. When a
    # claim creates an XR its external name will automatically be propagated to
    # the XR. Whether and how the external name is propagated to the resources
    # the XR composes is up to its Composition.
    crossplane.io/external-name: production-jenkins-0
spec:
  parameters:
    storageSize: "1Gi"
  compositionRef:
    name: jstack-production
