apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: grafana
spec:
  providerConfigRef:
    name: helm-provider
  forProvider:
    chart:
      name: loki
      repository: https://grafana.github.io/helm-charts
      version: 2.7.0
    namespace: ci
    wait: true


